# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: Check for updates

on:
  workflow_dispatch:
  schedule:
    - cron: "38 4 * * 6"  # every Saturday at 04:38 UTC   <https://crontab.guru/#38_4_*_*_6>

  # FIXME: temporary, just for testing
  pull_request:
    branches: ["**"]

permissions:
  contents: write
  pull-requests: write

env:
  UPDATE_BRANCH_NAME: "autoupdate"

jobs:

  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: pcrockett/setup-just@bfd0f2be2991d96e39d8d4c3bba4018d44857339  # v0.1.0

      - run: |
          git log --all --graph --format=format:'%C(dim white)⟵  %C(reset)%C(bold blue)%h%C(reset)%C(auto)%d%C(reset) %C(bold cyan)%an%C(reset) %C(bold magenta)%cs
          %C(bold blue)   ⎩ %C(reset)%s'
          if ! git switch "${UPDATE_BRANCH_NAME}"; then
            git switch --create "${UPDATE_BRANCH_NAME}" main
          fi

          just update
          if [ "$(git status --porcelain)" == "" ]; then
            echo "Already current!"
            exit 0
          fi

          # TODO: parse action.yml, get new version number, put in title and commit
          git add .
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Version bump"
          git push origin "${UPDATE_BRANCH_NAME}"

          pr_title="Version bump ${new_version}"
          if gh pr view >/dev/null 2>&1; then
            gh pr edit --title "${pr_title}"
          else
            gh pr create --title "${pr_title}" --body ""
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
